<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\content_email_notice\EmailNotice;

function content_email_notice_entity_insert(EntityInterface $entity) {
  $subscriber = \Drupal::service('content_email_notice.subscriber');
  $subscriber->onEmail($entity);
}

function content_email_notice_mail($key, &$message, $params) {
  $mail = \Drupal::service('content_email_notice.mail');
  $mail->mail($key, $message, $params);
}
